# Generated by Django 5.1.3 on 2024-11-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
